[[redirects]]
  from = "/pogo"
  to = "https://pogotes-moi-cette-fonte.netlify.app/"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  headers = {Access-Control-Allow-Origin= "*"}

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"